/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProfilesController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProfilesController_update"];
        trace?: never;
    };
    "/api/v1/media/image-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/video-uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_createVideoUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/video-assets/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_completeVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/video-assets/{assetId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/operations/video-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_queueOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/operations/video-assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_processingOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/operations/video-assets/{assetId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_retryProcessing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/assets/{assetId}/hls/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_hls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/assets/{assetId}/hls/{rendition}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_hlsVariant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/assets/{assetId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/assets/{assetId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SocialController_follow"];
        post?: never;
        delete: operations["SocialController_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SocialController_like"];
        post?: never;
        delete: operations["SocialController_unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SocialController_save"];
        post?: never;
        delete: operations["SocialController_unsave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SocialController_block"];
        post?: never;
        delete: operations["SocialController_unblock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CommentsController_list"];
        put?: never;
        post: operations["CommentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/posts/{postId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ModerationController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ModerationController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness check */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness check including PostgreSQL */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse public posts using a stable cursor */
        get: operations["FeedController_discover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse posts from followed creators */
        get: operations["FeedController_following"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PostsController_createImagePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View one public published post */
        get: operations["PostsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeController_list"];
        put?: never;
        post: operations["HomeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/videos/{videoId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HomeController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/videos/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HomeController_collections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesController_list"];
        put?: never;
        post: operations["SeriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesController_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesController_manage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["SeriesController_update"];
        trace?: never;
    };
    "/api/v1/series/{seriesId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}/submissions/{submissionId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesController_withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}/single-work/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesController_attachSingleWork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{seriesId}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesController_createEpisode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/episodes/{episodeId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesController_publishEpisode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/episodes/{episodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesController_findEpisode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/series-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesAdminController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/series-submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeriesAdminController_find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/series-submissions/{submissionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesAdminController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/series-submissions/{submissionId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeriesAdminController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published Shortforms */
        get: operations["ShortformsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortforms/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShortformsController_createVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortforms/{shortformId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShortformsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortforms/{shortformId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View one published Shortform */
        get: operations["ShortformsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community-posts/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CommunityController_createImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Post Home or one managed Category */
        get: operations["CommunityController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community-posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View one published Community Post */
        get: operations["CommunityController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active Community Categories */
        get: operations["CommunityController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagement/{targetType}/{targetId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["EngagementController_like"];
        post?: never;
        delete: operations["EngagementController_unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagement/{targetType}/{targetId}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["EngagementController_save"];
        post?: never;
        delete: operations["EngagementController_unsave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagement/{targetType}/{targetId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EngagementController_listComments"];
        put?: never;
        post: operations["EngagementController_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagement/{targetType}/{targetId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EngagementController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example creator@example.com */
            email: string;
            /** @example creator.one */
            handle: string;
            /** @example Creator One */
            displayName: string;
            password: string;
        };
        AuthUserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            handle: string;
            displayName: string;
            bio: string;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "MEMBER" | "MODERATOR" | "ADMIN";
        };
        LoginDto: Record<string, never>;
        PublicProfileDto: {
            /** Format: uuid */
            id: string;
            handle: string;
            displayName: string;
            bio: string;
            avatarUrl: string | null;
            postCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateProfileDto: Record<string, never>;
        CreateImageUploadDto: {
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            byteSize: number;
        };
        UploadSessionDto: {
            /** Format: uuid */
            assetId: string;
            uploadUrl: string;
            expiresInSeconds: number;
            requiredHeaders: Record<string, never>;
        };
        CreateVideoUploadDto: {
            /** @enum {string} */
            contentType: "video/mp4" | "video/quicktime" | "video/webm";
            byteSize: number;
            /**
             * @default LONG_VIDEO
             * @enum {string}
             */
            purpose: "LONG_VIDEO" | "SHORT_VIDEO";
        };
        MediaAssetStatusDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING_UPLOAD" | "UPLOADED" | "PROCESSING" | "READY" | "FAILED" | "DELETED";
            failureCode: Record<string, never> | null;
            playbackUrl: Record<string, never> | null;
            posterUrl: Record<string, never> | null;
        };
        VideoQueueCountsDto: {
            waiting: number;
            active: number;
            completed: number;
            failed: number;
            delayed: number;
            waitingChildren: number;
        };
        VideoProcessingOperationDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING_UPLOAD" | "UPLOADED" | "PROCESSING" | "READY" | "FAILED" | "DELETED";
            pipelineVersion: number;
            failureCode: Record<string, never> | null;
            failureMessage: Record<string, never> | null;
            processedAt: Record<string, never> | null;
            jobState: Record<string, never> | null;
            attemptsMade: number;
        };
        CreateCommentDto: Record<string, never>;
        /** @enum {string} */
        ReportReason: "SPAM" | "HARASSMENT" | "NUDITY" | "VIOLENCE" | "COPYRIGHT" | "OTHER";
        CreateReportDto: {
            reason: components["schemas"]["ReportReason"];
        };
        /** @enum {string} */
        PostFormat: "IMAGE" | "SHORT_VIDEO" | "LONG_VIDEO";
        Object: Record<string, never>;
        CreatorSummaryDto: {
            id: string;
            handle: string;
            displayName: string;
            avatarUrl?: string | null;
        };
        MediaSummaryDto: {
            id: string;
            url: string;
            mimeType: string;
            width: number;
            height: number;
            durationMs?: number | null;
            posterUrl?: string | null;
        };
        SeriesSummaryDto: {
            id: string;
            title: string;
            episodeNumber: number;
            episodeCount: number;
        };
        FeedItemDto: {
            id: string;
            format: components["schemas"]["PostFormat"];
            title?: string | null;
            caption: string;
            publishedAt: string;
            likeCount: number;
            commentCount: number;
            author: components["schemas"]["CreatorSummaryDto"];
            media: components["schemas"]["MediaSummaryDto"][];
            series?: components["schemas"]["SeriesSummaryDto"] | null;
        };
        DiscoveryFeedDto: {
            items: components["schemas"]["FeedItemDto"][];
            nextCursor?: string | null;
        };
        CreateImagePostDto: {
            /** Format: uuid */
            assetId: string;
            caption: string;
        };
        PlayableDto: {
            /** @enum {string} */
            kind: "HOME_VIDEO" | "SERIES" | "SERIES_EPISODE";
            /**
             * Format: uuid
             * @description Product-domain playable ID
             */
            id: string;
            media: components["schemas"]["MediaSummaryDto"];
        };
        EngagementTargetDto: {
            /** @enum {string} */
            type: "HOME_VIDEO" | "SERIES" | "SERIES_EPISODE" | "SHORTFORM" | "COMMUNITY_POST";
            /**
             * Format: uuid
             * @description Product-domain entity ID
             */
            id: string;
        };
        HomeVideoDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "UNLISTED" | "ARCHIVED" | "REMOVED";
            publishedAt: string;
            creator: components["schemas"]["CreatorSummaryDto"];
            media: components["schemas"]["MediaSummaryDto"];
            playable: components["schemas"]["PlayableDto"];
            engagementTarget: components["schemas"]["EngagementTargetDto"];
            likeCount: number;
            commentCount: number;
        };
        HomeVideoListDto: {
            items: components["schemas"]["HomeVideoDto"][];
        };
        CreateHomeVideoDto: {
            /** Format: uuid */
            assetId: string;
            title: string;
            description: string;
        };
        HomeVideoDraftDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "UNLISTED" | "ARCHIVED" | "REMOVED";
            /** Format: uuid */
            assetId: string;
        };
        CollectionItemDto: {
            position: number;
            video: components["schemas"]["HomeVideoDto"];
        };
        CollectionDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            owner: components["schemas"]["CreatorSummaryDto"];
            publishedAt: string;
            items: components["schemas"]["CollectionItemDto"][];
        };
        CollectionListDto: {
            items: components["schemas"]["CollectionDto"][];
        };
        SeriesEpisodeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            seriesId: string;
            episodeNumber: number;
            seasonEpisodeNumber?: number | null;
            title: string;
            synopsis: string;
            publishedAt?: string | null;
            media?: components["schemas"]["MediaSummaryDto"] | null;
            playable?: components["schemas"]["PlayableDto"] | null;
            engagementTarget?: components["schemas"]["EngagementTargetDto"] | null;
        };
        SeriesDto: {
            /** Format: uuid */
            id: string;
            title: string;
            synopsis: string;
            /** @enum {string} */
            workType: "SINGLE_WORK" | "EPISODIC";
            /** @enum {string} */
            publicationStatus: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "UNLISTED" | "ARCHIVED" | "REMOVED";
            genres: string[];
            tags: string[];
            ageRating?: string | null;
            releaseDate?: string | null;
            creator: components["schemas"]["CreatorSummaryDto"];
            singleWork?: components["schemas"]["PlayableDto"] | null;
            engagementTarget: components["schemas"]["EngagementTargetDto"];
            episodes: components["schemas"]["SeriesEpisodeDto"][];
        };
        SeriesListDto: {
            items: components["schemas"]["SeriesDto"][];
        };
        CreateSeriesDto: {
            title: string;
            synopsis: string;
            /** @enum {string} */
            workType: "SINGLE_WORK" | "EPISODIC";
            description?: string;
            genres?: string[];
            tags?: string[];
            ageRating?: Record<string, never> | null;
            productionInfo?: {
                [key: string]: unknown;
            };
            releaseDate?: Record<string, never> | null;
        };
        SeriesSubmissionDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED" | "APPROVED" | "REJECTED" | "WITHDRAWN";
            submittedAt?: string | null;
            reviewedAt?: string | null;
            decisionReason?: string | null;
            reviewer?: components["schemas"]["CreatorSummaryDto"] | null;
        };
        ManagedSeriesDto: {
            /** Format: uuid */
            id: string;
            title: string;
            synopsis: string;
            description: string;
            /** @enum {string} */
            workType: "SINGLE_WORK" | "EPISODIC";
            /** @enum {string} */
            publicationStatus: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "UNLISTED" | "ARCHIVED" | "REMOVED";
            genres: string[];
            tags: string[];
            ageRating?: string | null;
            productionInfo?: {
                [key: string]: unknown;
            } | null;
            releaseDate?: string | null;
            hasPlayableContent: boolean;
            canManageContent: boolean;
            createdAt: string;
            updatedAt: string;
            submissions: components["schemas"]["SeriesSubmissionDto"][];
            latestSubmission?: components["schemas"]["SeriesSubmissionDto"] | null;
        };
        ManagedSeriesListDto: {
            items: components["schemas"]["ManagedSeriesDto"][];
        };
        UpdateSeriesDto: {
            title?: string;
            synopsis?: string;
            /** @enum {string} */
            workType?: "SINGLE_WORK" | "EPISODIC";
            description?: string;
            genres?: string[];
            tags?: string[];
            ageRating?: Record<string, never> | null;
            productionInfo?: {
                [key: string]: unknown;
            };
            releaseDate?: Record<string, never> | null;
        };
        AttachSingleWorkVideoDto: {
            /** Format: uuid */
            assetId: string;
        };
        SeriesMediaDraftDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assetId: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "UNLISTED" | "ARCHIVED" | "REMOVED";
        };
        CreateSeriesEpisodeDto: {
            /** Format: uuid */
            assetId: string;
            episodeNumber: number;
            /** Format: uuid */
            seasonId?: string | null;
            seasonEpisodeNumber?: number | null;
            title: string;
            synopsis: string;
        };
        AdminSeriesSubmissionDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED" | "APPROVED" | "REJECTED" | "WITHDRAWN";
            submittedAt?: string | null;
            reviewedAt?: string | null;
            decisionReason?: string | null;
            reviewer?: components["schemas"]["CreatorSummaryDto"] | null;
            series: components["schemas"]["ManagedSeriesDto"];
            applicant: components["schemas"]["CreatorSummaryDto"];
        };
        AdminSeriesSubmissionListDto: {
            items: components["schemas"]["AdminSeriesSubmissionDto"][];
        };
        ReviewSeriesSubmissionDto: {
            reason: string;
        };
        ShortformPromotionDto: {
            /** @enum {string} */
            kind: "HOME_VIDEO" | "SERIES" | "SERIES_EPISODE";
            /** Format: uuid */
            id: string;
            title: string;
        };
        ShortformDto: {
            /** Format: uuid */
            id: string;
            engagementTarget: components["schemas"]["EngagementTargetDto"];
            /** @enum {string} */
            type: "VIDEO" | "IMAGE_CAROUSEL";
            title?: string | null;
            description: string;
            /** @description External music catalog reference */
            musicKey?: string | null;
            publishedAt: string;
            likeCount: number;
            commentCount: number;
            creator: components["schemas"]["CreatorSummaryDto"];
            media: components["schemas"]["MediaSummaryDto"][];
            promotedContent?: components["schemas"]["ShortformPromotionDto"] | null;
        };
        ShortformListDto: {
            items: components["schemas"]["ShortformDto"][];
        };
        CreateVideoShortformDto: {
            /** Format: uuid */
            assetId: string;
            title?: string;
            description: string;
            musicKey?: string;
            /** @enum {string} */
            promotedKind?: "HOME_VIDEO" | "SERIES" | "SERIES_EPISODE";
            /** Format: uuid */
            promotedId?: string;
        };
        ShortformDraftDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assetId: string;
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "UNLISTED" | "ARCHIVED" | "REMOVED";
        };
        CreateCommunityImagePostDto: {
            /** Format: uuid */
            assetId: string;
            caption: string;
            categorySlug?: string;
        };
        CommunityCategoryDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
        };
        CommunityPostDto: {
            /** Format: uuid */
            id: string;
            engagementTarget: components["schemas"]["EngagementTargetDto"];
            /** @enum {string} */
            type: "TEXT" | "IMAGE" | "VIDEO" | "LINK";
            body: string;
            linkUrl?: string | null;
            publishedAt: string;
            likeCount: number;
            commentCount: number;
            author: components["schemas"]["CreatorSummaryDto"];
            category?: components["schemas"]["CommunityCategoryDto"] | null;
            media: components["schemas"]["MediaSummaryDto"][];
        };
        CommunityPostListDto: {
            items: components["schemas"]["CommunityPostDto"][];
        };
        CommunityCategoryListDto: {
            items: components["schemas"]["CommunityCategoryDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfilesController_find: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfileDto"];
                };
            };
        };
    };
    ProfilesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfileDto"];
                };
            };
        };
    };
    MediaController_createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImageUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionDto"];
                };
            };
        };
    };
    MediaController_createVideoUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVideoUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionDto"];
                };
            };
        };
    };
    MediaController_completeVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetStatusDto"];
                };
            };
        };
    };
    MediaController_queueOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoQueueCountsDto"];
                };
            };
        };
    };
    MediaController_processingOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoProcessingOperationDto"];
                };
            };
        };
    };
    MediaController_retryProcessing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoProcessingOperationDto"];
                };
            };
        };
    };
    MediaController_hls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_hlsVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
                rendition: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_like: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_unlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_unsave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_block: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SocialController_unblock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    FeedController_discover: {
        parameters: {
            query?: {
                format?: components["schemas"]["PostFormat"];
                /** @description Opaque cursor returned by the previous page */
                cursor?: string;
                limit?: components["schemas"]["Object"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryFeedDto"];
                };
            };
        };
    };
    FeedController_following: {
        parameters: {
            query?: {
                format?: components["schemas"]["PostFormat"];
                /** @description Opaque cursor returned by the previous page */
                cursor?: string;
                limit?: components["schemas"]["Object"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryFeedDto"];
                };
            };
        };
    };
    PostsController_createImagePost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImagePostDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedItemDto"];
                };
            };
            /** @description Post does not exist or is not public */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeVideoListDto"];
                };
            };
        };
    };
    HomeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHomeVideoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeVideoDraftDto"];
                };
            };
        };
    };
    HomeController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                videoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeVideoDto"];
                };
            };
        };
    };
    HomeController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                videoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeVideoDto"];
                };
            };
            /** @description Home video is not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeController_collections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListDto"];
                };
            };
        };
    };
    SeriesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesListDto"];
                };
            };
        };
    };
    SeriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeriesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedSeriesDto"];
                };
            };
        };
    };
    SeriesController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedSeriesListDto"];
                };
            };
        };
    };
    SeriesController_manage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedSeriesDto"];
                };
            };
        };
    };
    SeriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDto"];
                };
            };
            /** @description Series is not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSeriesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedSeriesDto"];
                };
            };
        };
    };
    SeriesController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesSubmissionDto"];
                };
            };
        };
    };
    SeriesController_withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesSubmissionDto"];
                };
            };
        };
    };
    SeriesController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDto"];
                };
            };
        };
    };
    SeriesController_attachSingleWork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachSingleWorkVideoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesMediaDraftDto"];
                };
            };
        };
    };
    SeriesController_createEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seriesId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeriesEpisodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesMediaDraftDto"];
                };
            };
        };
    };
    SeriesController_publishEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesEpisodeDto"];
                };
            };
        };
    };
    SeriesController_findEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesEpisodeDto"];
                };
            };
            /** @description Episode is not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeriesAdminController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSeriesSubmissionListDto"];
                };
            };
        };
    };
    SeriesAdminController_find: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSeriesSubmissionDto"];
                };
            };
        };
    };
    SeriesAdminController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSeriesSubmissionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSeriesSubmissionDto"];
                };
            };
        };
    };
    SeriesAdminController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSeriesSubmissionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSeriesSubmissionDto"];
                };
            };
        };
    };
    ShortformsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortformListDto"];
                };
            };
        };
    };
    ShortformsController_createVideo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVideoShortformDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortformDraftDto"];
                };
            };
        };
    };
    ShortformsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortformId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortformDto"];
                };
            };
        };
    };
    ShortformsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortformId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortformDto"];
                };
            };
            /** @description Shortform is not published or does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_createImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommunityImagePostDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_list: {
        parameters: {
            query?: {
                /** @description Category slug. Omit for Post Home. */
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityPostListDto"];
                };
            };
        };
    };
    CommunityController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityPostDto"];
                };
            };
            /** @description Community Post is not published or does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommunityController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityCategoryListDto"];
                };
            };
        };
    };
    EngagementController_like: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EngagementController_unlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EngagementController_save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EngagementController_unsave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EngagementController_listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EngagementController_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EngagementController_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetType: string;
                targetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
